### ISSUE TITLE
clickhouse_connect doesn't work with pandas 2.1.0

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/clickhouse-connect#234]
### Describe the bug

`insert_df` fails with pandas 2.1.0 (I realize it just came out today) due to use of a removed (and I guess internal (?)) API.

### Steps to reproduce

```
In [1]: import pandas as pd

In [2]: import clickhouse_connect as cc

In [3]: client = cc.get_client()

In [4]: client.raw_query("create temporary table t (a Nullable(Timestamp))")
Out[4]: b''

In [5]: client.insert_df("t", pd.DataFrame({"a": [pd.Timestamp("now")]}))
  ...
AttributeError: module 'pandas.core.dtypes.common' has no attribute 'is_datetime_or_timedelta_dtype'
```

### Expected behaviour

I can insert a dataframe with timestamp columns

#### Environment
* clickhouse-connect version: 0.6.10
* Python version: 3.10.12
* Operating system: Linux

#### ClickHouse server
* ClickHouse Server version: 23.7.5.30
* ClickHouse Server non-default settings, if any: None that I am aware of
* `CREATE TABLE` statements for tables involved: See steps to reproduce

**Comment by genzgd** [comment]
Thanks for the report.  Our daily CI tests failed today as well so I'm actually in the middle of a fix :)
